export const ADD_MEMBERS = "ADD_MEMBERS";
export const ADD_MORE_MEMBERS = "ADD_MORE_MEMBERS";
export const CREATE_MEMBER = "CREATE_MEMBER";
export const PATCH_MEMBER = "PATCH_MEMBER";
export const CHANGE_SOCIAL_VIEW = "CHANGE_SOCIAL_VIEW";
